package com.ecopos.common;

import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * TelegramReporter — Gửi báo cáo kết quả test qua Telegram Bot
 *
 * Sử dụng biến môi trường:
 *   - TELEGRAM_BOT_TOKEN: Token của bot
 *   - TELEGRAM_CHAT_ID: Chat ID (hỗ trợ nhiều ID, phân cách bằng dấu phẩy)
 *   - REPORT_TITLE: Tiêu đề báo cáo (mặc định: "E2E TEST REPORT")
 */
public class TelegramReporter {

    /**
     * Thông tin 1 test case đã chạy
     */
    public record TestRow(String suite, String id, String title, String status, long durationMs, String error) {}

    /**
     * Gửi báo cáo tổng kết test qua Telegram
     *
     * @param rows danh sách kết quả test
     * @param totalDurationSec tổng thời gian chạy (giây)
     */
    public static void sendReport(List<TestRow> rows, double totalDurationSec) {
        String botToken = GlobalConstants.getEnv("TELEGRAM_BOT_TOKEN", "");
        String chatIds = GlobalConstants.getEnv("TELEGRAM_CHAT_ID", "");
        String reportTitle = GlobalConstants.getEnv("REPORT_TITLE", "E2E TEST REPORT");

        if (botToken.isBlank() || chatIds.isBlank()) {
            System.out.println("[Telegram] ⏭ Bỏ qua gửi Telegram (TELEGRAM_BOT_TOKEN hoặc TELEGRAM_CHAT_ID chưa cấu hình)");
            return;
        }

        // Thống kê
        long passed = rows.stream().filter(r -> "PASSED".equalsIgnoreCase(r.status())).count();
        long failed = rows.stream().filter(r -> "FAILED".equalsIgnoreCase(r.status())).count();

        long total = rows.size();
        int passRate = total > 0 ? (int) Math.round((passed * 100.0) / total) : 0;
        String iconHeader = failed > 0 ? "❌ FAIL" : "✅ PASS";
        String formattedDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss"));

        // Gom nhóm theo suite
        Set<String> suiteSet = new LinkedHashSet<>();
        rows.forEach(r -> suiteSet.add(r.suite()));

        StringBuilder suiteSummary = new StringBuilder();
        for (String suite : suiteSet) {
            long sPassed = rows.stream().filter(r -> suite.equals(r.suite()) && "PASSED".equalsIgnoreCase(r.status())).count();
            long sTotal = rows.stream().filter(r -> suite.equals(r.suite())).count();
            long sFailed = sTotal - sPassed;
            String icon = sFailed > 0 ? "⚠️" : "✅";
            suiteSummary.append(String.format("%s <b>%s</b>: %d/%d passed\n", icon, escHtml(suite), sPassed, sTotal));
        }

        // Chi tiết lỗi (nếu có)
        StringBuilder failSection = new StringBuilder();
        List<TestRow> failures = rows.stream().filter(r -> "FAILED".equalsIgnoreCase(r.status())).toList();
        if (!failures.isEmpty()) {
            failSection.append("\n\n🚨 <b>Failed Details:</b>\n");
            failures.stream().limit(5).forEach(f -> {
                String errMsg = f.error() != null ? f.error().substring(0, Math.min(60, f.error().length())) : "Unknown";
                failSection.append(String.format("- <code>%s</code>: %s\n  <i>%s...</i>\n",
                        escHtml(f.id()), escHtml(f.title()), escHtml(errMsg)));
            });
            if (failures.size() > 5) {
                failSection.append(String.format("...và %d lỗi khác.\n", failures.size() - 5));
            }
        }

        // Xây dựng message
        String msg = String.format("""
                🧪 <b>%s</b>
                -----------------------------------
                🏁 <b>Result:</b> %s
                🕒 <b>Time:</b> %s
                ⏱ <b>Duration:</b> %.1fs
                📊 <b>Summary:</b> %d Total | %d ✅ | %d ❌
                📈 <b>Pass Rate:</b> <b>%d%%</b>
                -----------------------------------
                📂 <b>By Suite:</b>
                %s%s-----------------------------------
                🚀 <i>Generated by EcoPOS E2E Java Runner</i>""",
                escHtml(reportTitle).toUpperCase(),
                iconHeader,
                formattedDate,
                totalDurationSec,
                total, passed, failed,
                passRate,
                suiteSummary,
                failSection);

        System.out.println("\n[Telegram] Message preview:\n" + msg);

        // Gửi cho từng chatId
        for (String chatId : chatIds.split(",")) {
            chatId = chatId.trim().replaceAll("[^\\d\\-]", "");
            if (chatId.isBlank()) continue;
            sendMessage(botToken, chatId, msg);
        }
    }

    /**
     * Gửi message tới 1 Telegram chat
     */
    private static void sendMessage(String botToken, String chatId, String text) {
        try {
            String apiUrl = String.format("https://api.telegram.org/bot%s/sendMessage", botToken);
            String payload = String.format("""
                    {"chat_id":"%s","text":"%s","parse_mode":"HTML"}""",
                    chatId,
                    text.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n"));

            HttpURLConnection conn = (HttpURLConnection) URI.create(apiUrl).toURL().openConnection();
            conn.setRequestMethod("POST");
            conn.setRequestProperty("Content-Type", "application/json; charset=UTF-8");
            conn.setDoOutput(true);

            try (OutputStream os = conn.getOutputStream()) {
                os.write(payload.getBytes(StandardCharsets.UTF_8));
            }

            int status = conn.getResponseCode();
            if (status == 200) {
                System.out.printf("[Telegram] ✅ Gửi thành công → ChatID: %s%n", chatId);
            } else {
                System.out.printf("[Telegram] ❌ Lỗi gửi: HTTP %d → ChatID: %s%n", status, chatId);
            }
        } catch (Exception e) {
            System.out.printf("[Telegram] 💥 Exception: %s%n", e.getMessage());
        }
    }

    /**
     * Escape HTML đặc biệt cho Telegram
     */
    private static String escHtml(String s) {
        if (s == null) return "";
        return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace("\"", "&quot;");
    }
}
